# Generated by Django 5.1.7 on 2025-03-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="название авто",
                    ),
                ),
                (
                    "car_num",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="номер авто"
                    ),
                ),
                (
                    "oil_type",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="тип топлива"
                    ),
                ),
                (
                    "l100km",
                    models.FloatField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="расход топлива летом",
                    ),
                ),
                (
                    "l100km_w",
                    models.FloatField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="расход топлива зимой",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автомобиль",
                "verbose_name_plural": "Автомобили",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="дата начала",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="дата окончания",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="описание события",
                    ),
                ),
                (
                    "calendar_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="имя календаря",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="место события в календаре",
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="участник в календаре",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие в календаре",
                "verbose_name_plural": "События в календаре",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="название компании",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Место назначения",
                "verbose_name_plural": "Места назначения",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="ФИО водителя",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="way_bills_creator.car",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Водитель",
                "verbose_name_plural": "Водители",
            },
        ),
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loc_km",
                    models.FloatField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="расстояние в км",
                    ),
                ),
                (
                    "loc_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loc_from",
                        to="way_bills_creator.location",
                        verbose_name="путь от",
                    ),
                ),
                (
                    "loc_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loc_to",
                        to="way_bills_creator.location",
                        verbose_name="путь до",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дистанция",
                "verbose_name_plural": "Дистанции",
            },
        ),
        migrations.CreateModel(
            name="WayBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="дата путевого листа",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="расстояние в км",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="way_bills_creator.car",
                        verbose_name="автомобиль",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="way_bills_creator.driver",
                        verbose_name="водитель",
                    ),
                ),
                (
                    "location_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_from",
                        to="way_bills_creator.location",
                        verbose_name="место от",
                    ),
                ),
                (
                    "location_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_to",
                        to="way_bills_creator.location",
                        verbose_name="место до",
                    ),
                ),
            ],
            options={
                "verbose_name": "Путевой лист",
                "verbose_name_plural": "Путевые листы",
            },
        ),
    ]
