# Generated by Django 5.1.7 on 2025-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("way_bills_creator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.PositiveIntegerField(
                default=1, unique=True, verbose_name="id из TeamUp"
            ),
            preserve_default=False,
        ),
    ]
