# Generated by Django 5.1.7 on 2025-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("way_bills_creator", "0004_alter_event_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="название места"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="адрес"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="название компании"
            ),
        ),
    ]
