# Generated by Django 5.1.7 on 2025-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "way_bills_creator",
            "0006_driver_lic_date_driver_lic_num_driver_snils_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="lic_date",
            field=models.CharField(
                blank=True, null=True, verbose_name="дата выдачи водительских прав"
            ),
        ),
    ]
