# Generated by Django 5.1.7 on 2025-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("way_bills_creator", "0007_alter_driver_lic_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="waybill",
            name="event_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="id из TeamUp"
            ),
        ),
    ]
