# Generated by Django 5.1.7 on 2025-04-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("way_bills_creator", "0008_waybill_event_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waybill",
            options={
                "ordering": ["date", "driver"],
                "verbose_name": "Путевой лист",
                "verbose_name_plural": "Путевые листы",
            },
        ),
    ]
